#The below code is the compiler: g++ is used for compiling C++ code
CXX = g++             
#The below code is Flags: -Wall enables all compiler warnings, -g includes debugging information
CXXFLAGS = -Wall -g    
# The below code is about Source files
SRCS = Main.cpp Graph.cpp
# The below code is the List of object files generated by replacing .cpp with .o
OBJS = $(SRCS:.cpp=.o)
# The below code is about Header files
HEADERS = Graph.h
# The below code is the name of the target executable
TARGET = dijkstra

# The below code is the build the target executable
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJS)

# The below code is the rule to build object files from corresponding source files
%.o: %.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) -c $<

# The below code is the rule to remove object files and the target executable
clean:
	rm -f $(OBJS) $(TARGET)
